from django.contrib.auth.models import User
import logging

class EmailBackend(object):

	# Requiremnts: we have to implement 2 methods for this class
	def authenticate(self, username=None, password=None):
		try:
			kwargs = {'email': username}
			user = User.objects.get(**kwargs)			
			
		# this exception is generated by default in django and not defined in User
		except User.DoesNotExist:
			return None
		
		if getattr(user, 'is_active') and user.check_password(password):
			return user
	
	# This method is used for checking if the current user  is authenticated in which we need the above method
	def get_user(self, user_id):
		try:
			return User.objects.get(pk=user_id)
		except User.DoesNotExist:
			return None